global_costmap:
    global_frame: map
    rolling_window: false
    static_map: true
    track_unknown_space: true

    update_frequency: 5.0
    publish_frequency: 5.0



    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: global_inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: global_obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
