base_local_planner: teb_local_planner/TebLocalPlannerROS
TebLocalPlannerROS:
  enable_homotopy_class_planning: false

  max_vel_x: 0.1
  max_vel_x_backwards: 0.1
  max_vel_theta: 1.0
  acc_lim_x: 0.1
  acc_lim_theta: 0.5

  weight_kinematics_forward_drive: 1000.0
  min_obstacle_dist: 0.15

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
